version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nestif:
      min-complexity: 5
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - gocognit
          - gocyclo
          - mnd
          - bodyclose
        path: _test\.go
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - govet
        text: 'shadow: declaration of "err"'
      - linters:
          - lll
        source: https?://
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
severity:
  default: error
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/amtp-protocol/agentry
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
