# AMTP Gateway Configuration Example
# Copy this file to config.yaml and customize for your environment

version: "1.0"

# Server configuration
server:
  address: ":8443"
  domain: "example.com"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# TLS configuration
tls:
  enabled: true
  cert_file: "/etc/ssl/certs/example.com.crt"
  key_file: "/etc/ssl/private/example.com.key"
  min_version: "1.3"

# DNS discovery configuration
dns:
  cache_ttl: "5m"
  timeout: "5s"
  resolvers:
    - "8.8.8.8:53"
    - "1.1.1.1:53"

# Message processing configuration
message:
  max_size: 10485760  # 10MB
  idempotency_ttl: "168h"  # 7 days
  validation_enabled: true

# Authentication configuration
auth:
  require_auth: false
  methods:
    - "domain"
    - "apikey"
  api_key_header: "X-API-Key"

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text

# Storage configuration
storage:
  type: "database"
  database:
    driver: "pgx"
    connection_string: "host=localhost port=5432 user=postgres password=postgres dbname=agentry sslmode=disable"
    max_connections: 100
    max_idle_time: 300
