server:
  address: ":8080"
  domain: "localhost"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

tls:
  enabled: false

dns:
  cache_ttl: 300s
  timeout: 5s
  resolvers: ["8.8.8.8:53", "8.8.4.4:53"]
  mock_mode: true
  mock_records:
    "example.com": "http://localhost:8081"
  allow_http: true

message:
  max_size: 10485760  # 10MB

auth:
  require_auth: false

logging:
  level: "debug"
  format: "json"

# Storage configuration
storage:
  type: "memory"

# Schema management configuration
schema:
  use_local_registry: true
  local_registry:
    base_path: "./schemas"
    index_file: "index.json"
    auto_save: true
    create_dirs: true
  cache:
    type: "memory"
    default_ttl: 3600s
    max_size: 1000
    cleanup_interval: 300s
  validation:
    enabled: true
    strict_mode: false
  negotiation:
    enabled: true
    fallback_strategy: "latest"
  compatibility:
    enabled: true
    strict_mode: false
  pipeline:
    enabled: true
    parallel_validation: true

  error_reporting:
    enabled: true
    include_payload: false
